init:
	flask db init --directory app/database/migrations
	
migrate:
	flask db migrate --directory app/database/migrations

upgrade:
	flask db upgrade --directory app/database/migrations

stamp:
	flask db stamp head --directory app/database/migrations
